twentysteps_auto_tables_update:
    path:     /update
    defaults: { _controller: twentystepsAutoTablesBundle:Crud:update }

twentysteps_auto_tables_add:
    path:     /add
    defaults: { _controller: twentystepsAutoTablesBundle:Crud:add }

twentysteps_auto_tables_remove:
    path:     /remove
    defaults: { _controller: twentystepsAutoTablesBundle:Crud:remove }
