services:
    twentysteps_bundle.AutoTablesBundle.services.entityinspectionservice:
        class: twentysteps\Bundle\AutoTablesBundle\Services\EntityInspectionService

    twentysteps_bundle.AutoTablesBundle.twig.autotables_extension:
        class: twentysteps\Bundle\AutoTablesBundle\Twig\AutoTablesExtension
        arguments: [@twentysteps_bundle.AutoTablesBundle.services.entityinspectionservice, @service_container]
        tags:
            - { name: twig.extension }